# Generated by Django 5.2.10 on 2026-02-06 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalColor",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("color_type", models.CharField(max_length=30)),
                ("mood", models.CharField(max_length=50)),
                ("good_color", models.CharField(max_length=100)),
                ("bad_color", models.CharField(max_length=100)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_colors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
