# Generated by Django 5.2.10 on 2026-02-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personalColors", "0003_alter_colorhistory_user_id_recentimages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colorhistory",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="recentimages",
            old_name="user_id",
            new_name="user",
        ),
    ]
