# Generated by Django 5.2.10 on 2026-02-10 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalColors", "0004_rename_user_id_colorhistory_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="favoriteImages",
            fields=[
                ("favorite_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "favorite_image",
                    models.ImageField(
                        blank=True, upload_to="personalColors/consistency/%Y/%m/%d/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
