# Generated by Django 5.2.10 on 2026-02-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personalColors", "0006_alter_recentimages_result_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorhistory",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
