"""
Django settings for PaletteMe project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-uu%s2d4$v9_6eh46$_(a0g*%)emx$sl%*jv5$eb3=1s)e(c(_p"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'accounts',
    'boards',
    'personalColors'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    'allauth.account.middleware.AccountMiddleware',  # 로그인 상태 확인을 request와 동기화
]

ROOT_URLCONF = "PaletteMe.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "PaletteMe.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'paletteme',
        'USER' : 'root',
        'PASSWORD' : '1234', # 설정한 비밀번호로 적어주면 된다.
        'HOST' : '127.0.0.1',
        'PORT' : '3306',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Seoul"  # ✅ 한국 시간으로 맞춤
USE_I18N = True
USE_TZ = True


# ✅ Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

# 프로젝트 전역 static 폴더(선택): BASE_DIR/static
# - 너가 이미 STATICFILES_DIRS를 쓰고 있으니 유지
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# (기본값이지만 명시해둠) 앱 내부 static도 찾게 해줌
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_AUTHENTICATION_METHOD = 'username'  # 로그인 할때 사용할 필드: 아이디
ACCOUNT_USERNAME_REQUIRED = True  # 회원가입 할때 아이디를 꼭 입력받겠다
ACCOUNT_EMAIL_REQUIRED = True  # 회원가입 할때 이메일을 꼭 입력받겠다
ACCOUNT_EMAIL_VERIFICATION = 'none' # 가입 후 이메일 보내겠다 (이메일 인증 필요 X)

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


ACCOUNT_FORMS = {  # 회원가입 할때 allauth 대신 CustomSignupForm 사용
    'signup': 'accounts.forms.CustomSignupForm',
}

AUTH_USER_MODEL = 'accounts.CustomUser'  # 기본 auth.User 대신 auth.CustomUser 사용

LOGIN_REDIRECT_URL = "/"  # 내 커스텀 로그인 페이지를 써야할때
ACCOUNT_LOGIN_REDIRECT_URL = "/"  # allauth 기본 탬플릿으로 로그인 후 리다이렉트 > 메인페이지로 감
ACCOUNT_LOGOUT_REDIRECT_URL = "/"  # allauth 기본 탬플릿으로 로그아웃 후 리다이렉트 > 메인페이지로 감

# 회원가입 성공 후 이동할 페이지 -> 메인페이지 (allauth는 회원가입 성공하면 자동 로그인함.)
ACCOUNT_SIGNUP_REDIRECT_URL = "/"