# Generated by Django 5.2.11 on 2026-02-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 등록된 이메일입니다.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': '이미 등록된 연락처입니다.'}, max_length=20, unique=True),
        ),
    ]
