# Generated by Django 5.2.11 on 2026-02-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': '이미 등록된 연락처입니다.'}, max_length=20, null=True, unique=True),
        ),
    ]
