# Generated by Django 5.2.10 on 2026-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, max_length=20, null=True, unique=True),
        ),
    ]
