# Generated by Django 5.2.10 on 2026-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/profileImg1.png', null=True, upload_to='profiles/'),
        ),
    ]
