# Generated by Django 5.2.10 on 2026-02-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/profileImg1.png', null=True, upload_to='profiles/'),
        ),
    ]
