# Generated by Django 5.2.10 on 2026-02-12 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_comment_like_post_qna_delete_qnapost_like_post_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="post_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="comment",
            name="comment_exactly_one_parent",
        ),
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_like_user_post",
        ),
        migrations.RemoveField(
            model_name="qna",
            name="is_anonymous",
        ),
        migrations.AddField(
            model_name="post",
            name="qna_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bug", "버그 제보"),
                    ("question", "사이트 관련 질문"),
                    ("suggestion", "건의 사항"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("FREE", "자유게시판"), ("QNA", "QnA")],
                default="FREE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "post")},
        ),
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="boards.post",
            ),
        ),
    ]
